### ISSUE TITLE
Allow me to log out elsewhere

### ISSUE THREAD

**Issue by ts4z** [ctm/mb2-doc#1030]
Pretty regularly, I log in from multiple locations and forget to log out from some of them. I would really like it if the "Already logged in elsewhere" feature allowed me to log out other logins.

As is, I can work around this if I happen to be able to log into my usual client box remotely, and kill the browser; or by planning ahead. Both are difficult.

(thanks!)

The above is the original issue. Here are the simple steps I think I need to implement it:
- [x] Create a dialog to bring up when the lobby receives an `Already Active` message
- [x] Add some bool parameter to `login_and_reconnect_common`, e.g. `override: bool`
- [x] Bubble the parameter upward
- [x] Add the bool to `nick_mapper::Login`
- [x] Wire that bool to the dialog
- [x] DRY up some of the code I wrote while exploring
- [x] Log out the existing session.
- [x] ~~[Log out the tables](https://github.com/ctm/mb2-doc/issues/1032).~~

**Comment by ctm** [comment]
I've deployed this, although with a bug (#1032) that I'll fix "soon".

**Comment by ctm** [comment]
Oh, and if it's convenient for you to test the new code, @ts4z, please do so. I've lightly tested it myself, but I have blind spots.

**Comment by ts4z** [comment]
Thanks! I'll likely run into this shortly.
