### ISSUE TITLE
Report had no rank

### ISSUE THREAD

**Issue by ctm** [ctm/mb2-doc#1223]
Fix so everyone has a rank.

<img width="598" alt="Screenshot 2023-09-26 at 06 48 31" src="https://github.com/ctm/mb2-doc/assets/26245/2e270771-c550-4dac-a449-0ef4532e4fcd">

That is how the [results from last night's tournament](https://craftpoker.com/event/4808/player/10) currently look.

**Comment by Asish-AP** [comment]
@ctm can you please specify the file frm where this results are coming . This is like very new to me but i want to contribute in this

**Comment by ctm** [comment]
I am sorry, @Asish-AP, but this is all associated with a private repository, so although I greatly appreciate your offer, you can't help, because it's closed source.

**Comment by ctm** [comment]
FWIW, the issue is that we're making the call `update_entries_and_payouts` from nickmapper, rather than from a tournament thread, so it's a race condition. In principle, NickMapper probably shouldn't make any calls to the database, since NickMapper is currently single threaded. In reality, eventually NickMapper should either spawn threads or we should use diesel-async since NickMapper needs to get to the database for some things. This, however, may not be one of them.

I no longer remember why NickMapper is doing this particular bit of db work, but it could have just been a misguided attempt on my part to make sure that we catch all messages that update ranks, since NickMapper is certain to see them. If so, I should find a better way to hoist that code out of NickMapper and not only will it solve our race condition, but it will also be a step in the right direction of getting rid of blocking code in NickMapper.

**Comment by ctm** [comment]
I'm pretty sure I can just add a Zero-Sized-Type that is only constructed in `update_entries_and_payouts` to each of the tuple messages we were snooping and that will force us to call that method. It's a little tricky in that `update_entries_and_payouts` is in models.rs, which is specific to mb2, so either I need to hoist that code to lib/commands, or I need to put something in lib/commands with an admonition to only use it from `update_entries_and_payouts`. I prefer just moving `update_entries_and_payouts`.

**Comment by ctm** [comment]
Moving `update_entries_and_payouts` was too complicated, so I added the ZST to `mb2_commands::types`, however, now that I'm fiddling around, I think the thing to do is to make a PaidFunMoney tuple of (FunMoney, Private) where Private is the ZST that can't be constructed. Then, rather than add Private to the message tuples we care about, we just change them from FunMoney to PaidFunMoney.

This will have the drawback that the actual PaidFunMoney constructors will be available throughout mb2_commands and mb2, but I'll give them names that should be sufficiently descriptive to prevent them being accidentally used.

**Comment by ctm** [comment]
Alas, although I like my ZST idea, some of the code in NickMapper couldn't be pulled out without a time consuming refactor. I _think_ the code that was in the way may actually be bit-rotted elimination code that never worked completely, but I don't want to risk it.

So, the solution was to push the all to `fixup_ranks` into NickMapper. Ugh.

Deploying now.
