### ISSUE TITLE
Registration issue . Forgot password

### ISSUE THREAD

**Issue by stonedonkey** [ctm/mb2-doc#140]
Would be nice to have a forgot password link

Obviously this goes near bottom of pile of things to worry about.

**Comment by ctm** [comment]
Agreed. At some point I'll make a milestone for must-have items like this. I have a ton of them in the back of my head.

In this particular case, I have chosen not to involve email for a few reasons.

**Comment by ctm** [comment]
Right now I'll make it so I can zap the password field so that the next login will accept whatever password the player provides. I can do that super quickly without having to introduce email into the equation. It won't scale, but it's an OK temporary measure.

**Comment by ctm** [comment]
Although there's no "forgot password" link, if I now truncate the `hash` column in the database for a player, that next time that player logs in, the password will be accepted and the new hash remembered.

IOW, I can manually make it so someone can set a new password. mb2 doesn't actually remember passwords, it only remembers password hashes, meaning if someone were to break into our database, they wouldn't get any passwords.

I'm closing this one for now.
