### ISSUE TITLE
Tournaments can be too long

### ISSUE THREAD

**Issue by ctm** [ctm/mb2-doc#1425]
Make it so that by default, levels always have the same duration.

- [x] Schema change
  - [x] Get rid of `soft_duration_cap_minutes` column in `events`
  - [x] Add a `unify_level_duration` column to `events`, make it `NOT NULL` and set the default to `true`
- [x] Update mb2 to respect that column
  - [x] Have `RunningEvent` use it
  - [x] ~~Have the tournament structure template API code~~
    - [x]  ~~_assume_ that it's in use (because it will be for the near future)~~
    - [x] ~~have a way to override, e.g. via a query string~~
  - [x] Put in a hack that totally ignores the different durations that the api properly returns
- [x] Update the documentation

[&hellip;lengthy consideration of worse alternatives deleted&hellip;]

**Comment by amanjyaku** [comment]
Accelerate the betting increments so that every time someone busts out, they double.

**Comment by ctm** [comment]
> Accelerate the betting increments so that every time someone busts out, they double.

I think that would make for a worse experience. I think we'll get good enough results from just keeping a constant duration throughout. The betting increments (stakes) rise as levels change, anyway.

**Comment by ctm** [comment]
I've deployed mb2 and am updating the documentation "now".
