### ISSUE TITLE
more sounds

### ISSUE THREAD

**Issue by ctm** [ctm/mb2-doc#398]
Crunch has requested a sound cue when a player is dealt a new hand.

Chiprider has requested a sound cue when the game changes.

I think to do this I'll want to make the bell into something different.  I haven't made this high priority or even attached it to a milestone. I'm hoping that after I get done with documentation I'll crank through a bunch of easy ones even if they're not high priority.

**Comment by ctm** [comment]
Not sure that I'll even get to the easy ones "soon". I did very little work on the documentation and there's a bunch of stuff to be done behind the scenes, and there's also FARGO coming up...

**Comment by kenkubey** [comment]
There should definitely be a sound for a game change.
Maybe a horn honk.

A recess bell for a Break would be nice too.

**Comment by ctm** [comment]
Noted. If you (@kenkubey), or anyone else, wants to hunt for sounds, a good place to look is [freesound](https://freesound.org/browse/). When searching, make sure to specify that you want a "Creative Commons 0" license. Here's a search (whose results I haven't looked at) for a recess bell that has a Creative Commons 0 license: [https://freesound.org/search/?g=1&q=recess&f=%20license:%22Creative+Commons+0%22](https://freesound.org/search/?g=1&q=recess&f=%20license:%22Creative+Commons+0%22)

If suitable Creative Commons 0 sounds are found, that _may_ bump the priority of this issue.

**Comment by ctm** [comment]
Aiyah! was kind enough to create an `m4a` for mb2 to use with game changes. I'll convert it into a wav and shoehorn it in. I'll make it active when the bell is green and worry about finer grain sound control later.

I'll get that particular sound integrated for this evening's game, but leave this issue open for other sounds and perhaps better controls over which sounds to play.

**Comment by ctm** [comment]
Deploying now.

**Comment by ctm** [comment]
Oops. I should only play the sound when the game changes and not when level changes and certainly not at the beginning of every hand...

**Comment by kenkubey** [comment]
I like it!  Thanks.

Sent from my iPhone

On Sep 15, 2020, at 5:22 PM, Clifford T. Matthews <notifications@github.com<mailto:notifications@github.com>> wrote:


Oops. I should only play the sound when the game changes and not when level changes and certainly not at the beginning of every hand...

**Comment by ctm** [comment]
I'm closing this, but I added a "shuffle sound" issue (#541).
