### ISSUE TITLE
Binglaha should have a delay after the die roll

### ISSUE THREAD

**Issue by kenkubey** [ctm/mb2-doc#453]
A one second or two second delay after the die roll would 
make it much easier for people to know if they are plating high-only
or high-low split.

A jpg of the die roll would be nice too.

**Comment by dkuznick** [comment]
Or put the result up in a pop up rather than / in addition to the chat window.

**Comment by ctm** [comment]
Now that we have a graphic for the die, I don't think the delay is wanted.
