### ISSUE TITLE
memory leak?

### ISSUE THREAD

**Issue by ctm** [ctm/mb2-doc#457]
After about five and a half hours, both "uncle al" and "big mike" had client lockups that were solved by closing their table windows. At the time, both were connected to Zoom, so it wasn't a loss of internet connectivity. This was deep into the tourney and into the (fun) money, so I didn't want to stop things and ask them to look for errors in the JavaScript Console or to bring up some sort of memory profiling tool.

I'm not marking this as high priority, but it's probably something that needs to be looked at.

**Comment by erb2000** [comment]
Suggest monitoring GDI objects. Maybe set up a test bed where two clients
simulate a long tournament, but maybe play at super speed.

**Comment by ctm** [comment]
@erb2000 Thanks. FWIW, I've been around the block before. See #112, for example.

**Comment by ctm** [comment]
I'm not going to look at this in the near future. I'll be replacing the client "soon". Even if I weren't, this hasn't happened since and there have been a zillion upgrades in the meantime.

Eventually it makes sense to do performance testing and when it does I'll open a separate issue for it.

BTW, [this](https://cprimozic.net/blog/speeding-up-webcola-with-webassembly/) is a super awesome article.
