### ISSUE TITLE
Allow game and limit pop ups to be moved outside of chat window. 

### ISSUE THREAD

**Issue by dkuznick** [ctm/mb2-doc#462]
It would be good to be able to move the game and limits pop ups so as not to cover the chat window.

**Comment by ctm** [comment]
I'm going to leave this open, but the current front-end will be replaced entirely with a more traditional one. I don't yet have a timeline for when it will happen. The current interface relies on UIKit and [UIKit](https://getuikit.com/docs/introduction) doesn't allow for notifications that are off the page.

**Comment by dkuznick** [comment]
👍

**Comment by ctm** [comment]
I've tagged this issue as `wontfix` and am closing it, like I'm doing with several other issues. It's worth thinking about for the new UI, but my plan is to have different issues for the new UI.
