### ISSUE TITLE
4-color deck preference

### ISSUE THREAD

**Issue by ctm** [ctm/mb2-doc#466]
TrayRacer:

> One other minor tweak: ideally I’d love Mb2 to permanently remember my preference for 4-color deck, but if that’s difficult, perhaps just remember it for the session – e.g. when changing tables.

deadhead:

> Yeah, that makes a lot of sense. Psychologically, there's a bunch of stuff that I know I need to do that I never put in the issue tracker because I don't want to be overwhelmed with all that stuff looming over me. OTOH, the way I "run" (ha!) 240 miles is knowing that there's a lot ahead of me but if I just keep moving I'll get there, so perhaps I shouldn't be such a big baby.

> Anyway, the issue of preferences is one of the comparatively few places where I need to actually think about an entirely new subsystem, which is one of user preferences, which obviously have some hierarchy. I.e., global preferences, vs. table preferences, vs. game preferences, with overrides, etc.

> I'll write up a hand-wavy issue but probably not do anything with it for a while. This is a place where I'll actually want to know who our target markets are before I do much work on.

> BTW, I thought four-color persisted through a table change, both due to my admittedly faulty memory but also due to knowing how the table is represented internally. I'm too lazy to check now, but if it's not following with a table change, I will probably fix that long before I work on a more general system of preferences.

**Comment by ctm** [comment]
I've marked this as high priority, because I need to make the color preference persist through table changes. I'm surprised that it doesn't, but it should be trivial for me to find and fix.

**Comment by ctm** [comment]
Color preference appears to persist through table changes. I just tried this by temporarily making the NLHE event be 3-handed, then firing up a demo with 4 players. That gave me two tables of two players. I set all four to be 4-color and then had one quit. The 4-color persisted across the table move.

I'm leaving this open, since we still need the ability to persist preferences, but since 4-color follows across table changes AFAICT, it's no longer high priority.

**Comment by clauclauclaudia** [comment]
Not sure if tacking this on here is correct, but I'd love to be able to view 4-color as an observer... either by having a persistent preference or by having a button in the observer window.

**Comment by ctm** [comment]
I've split @clauclauclaudia's comment into a separate issue (#514), but I do want to note that various EMBARGO Zoom participants reported that they lose the 4-color deck on table changes. I don't think I've ever seen that on Brave. Perhaps it's browser specific. Perhaps I'm just unobservant.

I was in a bit of a rush though, so I didn't ask which browsers people were using.

**Comment by ctm** [comment]
I don't plan on doing the rest of this one soon due to the lack of persistent preferences (#540).

**Comment by ctm** [comment]
I did this a while back and never closed this issue.
