### ISSUE TITLE
Finish some Better Explanations issues

### ISSUE THREAD

**Issue by ctm** [ctm/mb2-doc#606]
I still have some Better Explanations issues that are easy. Crank them out. Don't worry about harder ones; I'll push the deadline for Better Explanations out a little further.

**Comment by RandallWert** [comment]
I'm a first-time contributor. I'd be willing to take this on, if you can provide just the necessary guidance.

**Comment by ctm** [comment]
@RandallWert Hi Randall, I apologize for overlooking your response.

I'm not sure there's much for you to do. Are you an `mb2` user? If not, then it seems unlikely there's anything for you to do. If you are, I might be able to dig up something, but even then it seems unlikely.

Currently mb2 is pretty much a one man project. That will change in the future, although initially through contractors and then employees. It will remain closed-source for the indefinite future.

**Comment by RandallWert** [comment]
No problem! I'm not an mb2 user, so I'll pass on it. Best of luck with the project!
