### ISSUE TITLE
redeeming a lammer didn't immediately update my chips and lammers

### ISSUE THREAD

**Issue by ctm** [ctm/mb2-doc#749]
Fix it so that if a player redeems one or more lammers, that player's chips and lammers are updated in the graphical interface.

I had folded and I redeemed a lammer while the hand was being played by others. I saw the text message that said I had redeemed, but my chip count and lammer count didn't change until the end of the hand.

**Comment by gerdog** [comment]
I the real world this is how it would happen - tho in the interwebs our dealers are "more" experienced

**Comment by ctm** [comment]
Well, what currently happens is that if the player is out of a hand, that player can redeem a lammer in the middle of that hand and that does indeed happen, it's just that although the server does it and sends info to the client, the client doesn't actually update the UI. That's just a silly oversight on my part and I can fix this quickly (I just got sidetracked by chat (#748)).

**Comment by ctm** [comment]
If you're in the hand it schedules the redemption to occur before the next hand starts so that in both cases the player will have the chips before the start of the next hand, but they never increase chips while someone is in a hand.

**Comment by ctm** [comment]
Fixed. Deploying now.
