### ISSUE TITLE
suggest shortcut

### ISSUE THREAD

**Issue by jdkullmann** [ctm/mb2-doc#81]
how about 'k' as shortcut for check? I didn't see one in the list

**Comment by ctm** [comment]
Coming up.

**Comment by ctm** [comment]
Done, deployed and tested.

**Comment by ctm** [comment]
Oops. Need to update README.md

**Comment by ctm** [comment]
OK. I added k as a one letter alias for check. We already had an undocumented cx alias, but one letter is better than two, so I've kept them both.
